### ISSUE TITLE
High packet loss after upgrading to 3.11.16 version

### ISSUE THREAD

**Issue by vpalmisano** [versatica/mediasoup#1037]
## Bug Report
After upgrading to the last release (containing https://github.com/versatica/mediasoup/pull/1032), when running with limited networking I got a lot of warnings like these:

```
mediasoup:WARN:Channel [pid:1032678] RTC::RtpRetransmissionBuffer::Insert() | packet timestamp is higher than timestamp of immediate newer packet in the buffer, discarding it [ssrc:138048629, seq:14606, timestamp:2513086702] +52ms
RTC::RtpRetransmissionBuffer::Dump() | <RtpRetransmissionBuffer>
RTC::RtpRetransmissionBuffer::Dump() |   buffer [size:205, maxSize:5000]
RTC::RtpRetransmissionBuffer::Dump() |   oldest item [seq:14466, timestamp:2512420792]
RTC::RtpRetransmissionBuffer::Dump() |   newest item [seq:14670, timestamp:2512600792]
RTC::RtpRetransmissionBuffer::Dump() |   buffer window: 4294921574ms
RTC::RtpRetransmissionBuffer::Dump() | </RtpRetransmissionBuffer>
```

```
mediasoup:WARN:Channel [pid:1032678] RTC::RtpRetransmissionBuffer::Insert() | packet has less seq but higher timestamp than oldest packet in the buffer, discarding it [ssrc:409260887, seq:18365, timestamp:1026593387] +44ms
RTC::RtpRetransmissionBuffer::Dump() | <RtpRetransmissionBuffer>
RTC::RtpRetransmissionBuffer::Dump() |   buffer [size:165, maxSize:5000]
RTC::RtpRetransmissionBuffer::Dump() |   oldest item [seq:24816, timestamp:1024930187]
RTC::RtpRetransmissionBuffer::Dump() |   newest item [seq:24980, timestamp:1025106407]
RTC::RtpRetransmissionBuffer::Dump() |   buffer window: 1958ms
RTC::RtpRetransmissionBuffer::Dump() | </RtpRetransmissionBuffer>
```

Reading the last log I see that:
- the buffer state is: oldest item [seq:24816, timestamp:1024930187], newest item [seq:24980, timestamp:1025106407]
- new packet with seq:18365, timestamp:1026593387 is dropped
- seq:18365 probably belongs to a newer packet counted at the next cycle, so it should became the newest item in the buffer

**Comment by jmillan** [comment]
@vpalmisano is this happening in 3.11.15 or only in 3.11.16?

**Comment by ibc** [comment]
> is this happening in 3.11.15 or only in 3.11.16?

@jmillan which of those changes in 3.11.16 would you mean?

> * Fix `SeqManager`: Properly consider previous cycle dropped inputs ([PR #1032](https://github.com/versatica/mediasoup/pull/1032)).
> * `RtpRetransmissionBuffer`: Get rid of not necessary `startSeq` private member ([PR #1029](https://github.com/versatica/mediasoup/pull/1029)).

I don't think any of them can cause this issue, am I wrong?

**Comment by ibc** [comment]
@jmillan I'm a bit confused whether `RtpStream::ReceiveStreamPacket()` accepts or not a packet with a super newest timestamp but with a seq number that "looks" like old. Currently we are discarding it in `RtpRetransmissionBuffer` because there we assume that received packets have a seq number that must "respect" the current content of the buffer. We took this decision by assuming that, otherwise, the packet would **already** been discarded by `RtpStream::ReceiveStreamPacket()` before even trying to insert it into the buffer. However I don't see that's true:

```c++
bool RtpStream::ReceiveStreamPacket(RTC::RtpPacket* packet)
	{
		MS_TRACE();

		const uint16_t seq = packet->GetSequenceNumber();

		// If this is the first packet seen, initialize stuff.
		if (!this->started)
		{
			InitSeq(seq);

			this->started     = true;
			this->maxSeq      = seq - 1;
			this->maxPacketTs = packet->GetTimestamp();
			this->maxPacketMs = DepLibUV::GetTimeMs();
		}

		// If not a valid packet ignore it.
		if (!UpdateSeq(packet))
		{
			MS_WARN_TAG(
			  rtp,
			  "invalid packet [ssrc:%" PRIu32 ", seq:%" PRIu16 "]",
			  packet->GetSsrc(),
			  packet->GetSequenceNumber());

			return false;
		}

		// Update highest seen RTP timestamp.
		if (RTC::SeqManager<uint32_t>::IsSeqHigherThan(packet->GetTimestamp(), this->maxPacketTs))
		{
			this->maxPacketTs = packet->GetTimestamp();
			this->maxPacketMs = DepLibUV::GetTimeMs();
		}

		return true;
	}
```

```c++
bool RtpStream::UpdateSeq(RTC::RtpPacket* packet)
	{
		MS_TRACE();

		const uint16_t seq    = packet->GetSequenceNumber();
		const uint16_t udelta = seq - this->maxSeq;

		// If the new packet sequence number is greater than the max seen but not
		// "so much bigger", accept it.
		// NOTE: udelta also handles the case of a new cycle, this is:
		//    maxSeq:65536, seq:0 => udelta:1
		if (udelta < MaxDropout)
		{
			// In order, with permissible gap.
			if (seq < this->maxSeq)
			{
				// Sequence number wrapped: count another 64K cycle.
				this->cycles += RtpSeqMod;
			}

			this->maxSeq = seq;
		}
		// Too old packet received (older than the allowed misorder).
		// Or to new packet (more than acceptable dropout).
		else if (udelta <= RtpSeqMod - MaxMisorder)
		{
			// The sequence number made a very large jump. If two sequential packets
			// arrive, accept the latter.
			if (seq == this->badSeq)
			{
				// Two sequential packets. Assume that the other side restarted without
				// telling us so just re-sync (i.e., pretend this was the first packet).
				MS_WARN_TAG(
				  rtp,
				  "too bad sequence number, re-syncing RTP [ssrc:%" PRIu32 ", seq:%" PRIu16 "]",
				  packet->GetSsrc(),
				  packet->GetSequenceNumber());

				InitSeq(seq);

				this->maxPacketTs = packet->GetTimestamp();
				this->maxPacketMs = DepLibUV::GetTimeMs();
			}
			else
			{
				MS_WARN_TAG(
				  rtp,
				  "bad sequence number, ignoring packet [ssrc:%" PRIu32 ", seq:%" PRIu16 "]",
				  packet->GetSsrc(),
				  packet->GetSequenceNumber());

				this->badSeq = (seq + 1) & (RtpSeqMod - 1);

				// Packet discarded due to late or early arriving.
				this->packetsDiscarded++;

				return false;
			}
		}
		// Acceptable misorder.
		else
		{
			// Do nothing.
		}

		return true;
	}
```

**Comment by jmillan** [comment]
In `RtpStream::UpdateSeq()` the packet is discarded if its seq num is too old or too new.

We may want to know what 'too old' and 'too new' is though.

**Comment by jmillan** [comment]
> @jmillan which of those changes in 3.11.16 would you mean?

I just want to make sure when this behaviour started since @vpalmisano pointed this happened since `SeqManager` changes.

**Comment by ibc** [comment]
> In `RtpStream::UpdateSeq()` the packet is discarded if its seq num is too old or too new.

I don't see that it's discarded if too old. It is, but next one is accepted.

**Comment by ibc** [comment]
PR here https://github.com/versatica/mediasoup/pull/1039

**Comment by vpalmisano** [comment]
@jmillan it started happening after pulling this change https://github.com/versatica/mediasoup/pull/1032

**Comment by ibc** [comment]
> @jmillan it started happening after pulling this change #1032

So after the fixes in `SeqManager`. Honestly I fail to understand how those changes can affect here. The issue is clearly identified in my PR https://github.com/versatica/mediasoup/pull/1039 (test included simulating your very same scenario).

**Comment by jmillan** [comment]
>> @jmillan it started happening after pulling this change https://github.com/versatica/mediasoup/pull/1032

And it does not happen for 3.11.15?

> So after the fixes in SeqManager. Honestly I fail to understand how those changes can affect here. The issue is clearly identified in my PR https://github.com/versatica/mediasoup/pull/1039 (test included simulating your very same scenario).

`SeqManager` changes happened in `Input()` method, which generates the new sequence numbers used for outgoing RTP packets. So it could be related. I want to be sure if this behaviour started on 3.11.15 or not.

**Comment by vpalmisano** [comment]
Let me check with 3.11.15

**Comment by ibc** [comment]
I'm reopening this (it was closed after merging my PR). I'm 99% sure that the issue is not related to SeqManager anyway.

**Comment by vpalmisano** [comment]
It doesn't happen with 3.11.15

**Comment by ibc** [comment]
@vpalmisano I've reproduced your scenario in a test https://github.com/versatica/mediasoup/pull/1039/files#diff-785aacf963778c636ba27e6bfceb6e998d87e198788291ff0cef4c0de6efb901R233 added in al already merged and deployed PR (3.11.18). Perhaps the issue is connected to these changes in SeqManager and code in RetransmissionBuffer prior to my very latest fix (done 10 minutes ago), no idea.

Can you please test in 3.11.18?

**Comment by vpalmisano** [comment]
I'm testing with 3.11.18 and I saw no issues.

**Comment by ibc** [comment]
Cool, thanks. Closing then.

**Comment by vpalmisano** [comment]
(comment deleted by error)

I'm testing with 3.11.18 and I saw no issues. Thanks!

**Comment by vpalmisano** [comment]
I just saw this after some minutes:
```
  mediasoup:WARN:Channel [pid:1272954] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:843326883, seq:15046, ts:2231706788] from original [ssrc:568769515, seq:1161] +0ms                                                                                                                                                                                          
  mediasoup:WARN:Channel [pid:1272954] RTC::RtpStream::UpdateSeq() | too bad sequence number, re-syncing RTP [ssrc:843326883, seq:15047] +45ms                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:1272954] RTC::RtpRetransmissionBuffer::Insert() | packet has less seq but higher timestamp than oldest packet in the buffer, discarding it [ssrc:843326883, seq:15047, timestamp:2231710388] +0ms 
...
  mediasoup:WARN:Channel [pid:1272954] RTC::RtpRetransmissionBuffer::Insert() | packet has less seq but higher timestamp than oldest packet in the buffer, discarding it [ssrc:843326883, seq:17609, timestamp:2243226788]
....
```

After some errors the stream was received with 100% packet loss :(

**Comment by ibc** [comment]
Hell! Unfortunately I need `retransmissionBuffer->Dump()` output to figure out the problem. Can you provide it please?

**Comment by ibc** [comment]
> packet has less seq but higher timestamp than oldest packet in the buffer, discarding it

There is still a chance for this to happen: If the timestamp of the latest received packet is less that 2000ms older than newest packet in the buffer. In that case we still compare seq numbers following normal RTP rules.

The **thing** here is this:

```
RTC::RtpStream::UpdateSeq() | too bad sequence number, re-syncing RTP [ssrc:843326883, seq:15047]
mediasoup:WARN:Channel [pid:1272954] RTC::RtpRetransmissionBuffer::Insert() | packet has less seq but higher timestamp than oldest packet in the buffer, discarding it [ssrc:843326883, seq:15047, timestamp:2231710388] 
```

When `RtpStream::UpdateSeq()` re-syncs the stream it should notify its child classes (`RtpStreamRecv` and `RtpStreamSend`) so they can react on it. For instance, `RtpStreamSend` could clear the entire retransmission buffer to avoid these problems.

I'd LOVE to have a proper scenario (seq and timestamp values) that reproduce this problem.

**Comment by ibc** [comment]
BTW @vpalmisano which kind of super crazy scenario are you testing? In order to generate a RTP seq number roll up (not sure if the term is ok, I mean having a seq that looks older than another despite its timestamp is higher) I verified that you need to loose more than 2 consecutive seconds of audio. May your scenario trigger this?

**Comment by vpalmisano** [comment]
I'm simply testing 3 640x360 producers received by 1 consumer with downstream networking limited at 500Kbps, RTT=50ms (no audio, only video).

**Comment by ibc** [comment]
Aren't you applying network limit to the senders at all? In any direction? Because the retransmission buffer doesn't care at all about how packets are being sent to the consuming device.

**Comment by vpalmisano** [comment]
At sender side the limit is 10Mbps, RTT=50ms

**Comment by ibc** [comment]
And does the issue happen if no  bw limit is applied in receiver side? And if uplink limit is applied in senders?

**Comment by vpalmisano** [comment]
If we limit only the uplink we have no effect on the receiver side.

> In order to generate a RTP seq number roll up (not sure if the term is ok, I mean having a seq that looks older than another despite its timestamp is higher) I verified that you need to loose more than 2 consecutive seconds of audio

Probably for video it is different, because frames could be fragmented into multiple RTP packets. Anyway when I limit the downlink at 500Kbps I see that the receiver jitterbuffer increases up to 1-1.5s; at that point I start seeing the RtpRetransmissionBuffer warnings.

**Comment by ibc** [comment]
I'm gonna do a pending change but, in your scenario, does it behave worse than a few days or weeks ago?

**Comment by vpalmisano** [comment]
> does it behave worse than a few days or weeks ago?

Yep, definitively. At some point it triggers an ICE disconnection.

I'm trying to reproduce it with your mediasoup demo.

**Comment by vpalmisano** [comment]
You should be able to reproduce it:

```
sudo modprobe ifb numifbs=1
docker pull ghcr.io/vpalmisano/webrtcperf:devel

echo "setInterval(() => { document.querySelector('.button.mic.on')?.click(); }, 2000);" > /tmp/mediasoup.js

docker run -d --name senders \
    -v /dev/shm:/dev/shm \
    -v $HOME/.webrtcperf:/root/.webrtcperf \
    -v /tmp/mediasoup.js:/tmp/mediasoup.js:ro \
    --cap-add=NET_ADMIN \
    ghcr.io/vpalmisano/webrtcperf:devel \
    --url="https://v3demo.mediasoup.org/?roomId=fwdthyct&consume=false&forceVP9=true" \
    --tabs-per-session=3 \
    --show-page-log=false \
    --video-width=640 \
    --video-height=480 \
    --stats-interval=5 \
    --script-path=/tmp/mediasoup.js \
    --throttle-config='{"up":[{"protocol":"udp","rate":10000,"rtt":50,"loss":"0%","queue":20}],"down":[{"protocol":"udp","rate":10000,"rtt":50,"loss":"0%","queue":20},{"protocol":"udp","rate":500,"rtt":50,"loss":"0%","queue":20,"at":10}]}'

docker run -d --name receiver \
    -v /dev/shm:/dev/shm \
    -v $HOME/.webrtcperf:/root/.webrtcperf \
    --cap-add=NET_ADMIN \
    ghcr.io/vpalmisano/webrtcperf:devel \
    --url="https://v3demo.mediasoup.org/?roomId=fwdthyct&produce=false" \
    --tabs-per-session=1 \
    --show-page-log=false \
    --stats-interval=5 \
    --throttle-config='{"up":[{"protocol":"udp","rate":10000,"rtt":50,"loss":"0%","queue":20}],"down":[{"protocol":"udp","rate":10000,"rtt":50,"loss":"0%","queue":20},{"protocol":"udp","rate":500,"rtt":50,"loss":"0%","queue":20,"at":10}]}'

docker logs -f receiver || true
# <ctrl-c>
docker rm -f senders || true
docker rm -f receiver || true
```

**Comment by ibc** [comment]
Working on this: https://github.com/versatica/mediasoup/pull/1041

Will continue later. Regarding your code snippet above, I don't really know how to use it locally, or I should spend some time on it.

**Comment by ibc** [comment]
Yup, we got the core dump.

**Comment by ibc** [comment]
@vpalmisano this PR https://github.com/versatica/mediasoup/pull/1041 is merged in v3 and deployed in the demo server. I've added a test in `TestRtpStreamSend` that verifies it works as expected. I think it should fix the issue in your scenario. Can you please try it just one more time using your setup? If the issue still happens I'll spend my time making it work for me.

**Comment by ibc** [comment]
BTW I've tried a similar scenario with downlink limitation to 500kbps and RTT 50 and IMHO it behaves correctly (I mean, no worse than a few months ago). And there are just a very few logs about "seq and timestamp".

**Comment by ibc** [comment]
Also, this ongoing PR should avoid more corner cases so some of those warning logs: https://github.com/versatica/mediasoup/pull/1044

**Comment by vpalmisano** [comment]
> I think it should fix the issue in your scenario. Can you please try it just one more time using your setup? If the issue still happens I'll spend my time making it work for me.

It is still not working. I will double check the throttle configuration, but, anyway, with 3.11.15 version I got different results and I never go into a 100% packet loss state.

**Comment by ibc** [comment]
> It is still not working. I will double check the throttle configuration, but, anyway, with 3.11.15 version I got different results and I never go into a 100% packet loss state.

With the previous retransmission buffer implementation it may happen that packet loss looks lower but retransmitted packets belong to a previous seq cycle, meaning that they are super old packets.

The only doubt I have about the new implementation is the buffer max size (currently 2500 items) which is hardcoded in RtpStreamSend.cpp when it creates the RtpRettansmissionBuffer. Can you try increasing it to higher values and see how it behaves?

**Comment by jmillan** [comment]
We are writting a logger that will allow tracing data from reception to delivery. We'll have an initial impementation next week.

**Comment by vpalmisano** [comment]
Some details:
- the error starts happening after this event:
```
mediasoup:WARN:Channel [pid:3327113] RTC::RtpRetransmissionBuffer::Insert() | packet has lower seq but higher timestamp than newest packet in the buffer, emptying the buffer [ssrc:501216601, seq:14526, timestamp:1652329573] +77ms                                                                                                                                            
RTC::RtpRetransmissionBuffer::Dump() | <RtpRetransmissionBuffer>                                                                                                                                                                                                                                                                                                                   
RTC::RtpRetransmissionBuffer::Dump() |   buffer [size:182, maxSize:2500]                                                                                                                                                                                                                                                                                                           
RTC::RtpRetransmissionBuffer::Dump() |   oldest item [seq:15079, timestamp:1652142283]                                                                                                                                                                                                                                                                                             
RTC::RtpRetransmissionBuffer::Dump() |   newest item [seq:15260, timestamp:1652322283]                                                                                                                                                                                                                                                                                             
RTC::RtpRetransmissionBuffer::Dump() |   buffer window: 2000ms                                                                                                                                                                                                                                                                                                                     
RTC::RtpRetransmissionBuffer::Dump() | </RtpRetransmissionBuffer>
```

  Basically the inserted packet with seq:14526 is lower than seq:15260 but with newer timestamp. In this case increasing the buffer size doesn't help.

- After that, I see these strange warnings:
```
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpRetransmissionBuffer::Insert() | packet has too high seq and forces buffer emptying [ssrc:792350959, seq:16315, timestamp:3345566191] +25s                                                                                                                                                                                          
  mediasoup:WARN:Channel [pid:3327113] RTC::TransportCongestionControlClient::MayEmitAvailableBitrateEvent() | high BWE value decrease detected, notifying the listener [now:396015, before:555919] +13s                                                                                                                                                                           
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23213] +53s                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23213] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23213, ts:1519214758] from original [ssrc:382803750, seq:0] +0ms                                                                                                                                                                                             
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23215] +1ms                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23215] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23215, ts:1519214758] from original [ssrc:382803750, seq:1] +0ms                                                                                                                                                                                             
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23217] +1ms                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23217] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23217, ts:1519214758] from original [ssrc:382803750, seq:2] +1ms                                                                                                                                                                                             
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23219] +1ms                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23219] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23219, ts:1519214758] from original [ssrc:382803750, seq:3] +0ms                                                                                                                                                                                             
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23221] +1ms                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23221] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23221, ts:1519214758] from original [ssrc:382803750, seq:4] +0ms                                                                                                                                                                                             
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23223] +1ms                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23223] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23223, ts:1519214758] from original [ssrc:382803750, seq:5] +0ms                                                                                                                                                                                             
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23225] +1ms                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23225] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23225, ts:1519214758] from original [ssrc:382803750, seq:6] +0ms                                                                                                                                                                                             
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23227] +1ms                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23227] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23227, ts:1519214758] from original [ssrc:382803750, seq:7] +0ms                                                                                                                                                                                             
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23235] +256ms                                                                                                                                                                                                                                       
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23235] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23235, ts:1519236448] from original [ssrc:382803750, seq:17] +0ms                                                                                                                                                                                            
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:937745296, seq:23237] +3ms                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:937745296, seq:23237] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:937745296, seq:23237, ts:1519236448] from original [ssrc:382803750, seq:18] +0ms                                                                                                                                                                                            
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | too bad sequence number, re-syncing RTP [ssrc:937745296, seq:23238] +3ms                                                                                                                                                                                                                                      
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | bad sequence number, ignoring packet [ssrc:792350959, seq:15492] +18s                                                                                                                                                                                                                                         
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::ReceiveStreamPacket() | invalid packet [ssrc:792350959, seq:15492] +0ms                                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] RTC::SvcConsumer::SendRtpPacket() | failed to send packet [ssrc:792350959, seq:15492, ts:3353180281] from original [ssrc:402472184, seq:7313] +0ms                                                                                                                                                                                          
  mediasoup:WARN:Channel [pid:3327113] RTC::RtpStream::UpdateSeq() | too bad sequence number, re-syncing RTP [ssrc:792350959, seq:15493] +42ms                                                                                                                                                                                                                                     
  mediasoup:WARN:Channel [pid:3327113] webrtc::ProbeController::Process() | kWaitingForProbingResult: timeout +9s
```

  Is it possible that the seq restarts from 0?

**Comment by jmillan** [comment]
That 'too bad sequence number'  may be for the `SendRtpStream` which checks a sequence number created by `SeqManager`. I'm trying to reproduce this.

**Comment by jmillan** [comment]
I can't reproduce the problem. 

Please @vpalmisano, try this branch https://github.com/versatica/mediasoup/tree/RtcLogger. It will stdout a line per incoming `RtpPacket` indicating whether it was relayed and if not, the cause. It comes with incoming and outgoing sequence numbers.

Please provide us with the logs for the failing Consumer.

**Comment by vpalmisano** [comment]
Do I need to turn on some env variable to see the worker output?

**Comment by jmillan** [comment]
yes, if you use the lastest code. Please, check meson.build file. It's
there.

**Comment by vpalmisano** [comment]
The 100% packet loss starts happening at 2023-04-03T18:21:00:

[mediasoup.log.gz](https://github.com/versatica/mediasoup/files/11141604/mediasoup.log.gz)

**Comment by jmillan** [comment]
Thanks @vpalmisano . I'll check the logs tomorrow.

**Comment by jmillan** [comment]
TODO: We are not calling `rtpSeqManager.Drop()` everytime we should. We should call it in cosumers every time a packet of the stream being sent is dropped.

**Comment by jmillan** [comment]
STR with mediasoup-demo with single host:

Tab 1: roomId=loss&forceVP9=true&consume=false
Tab 2: roomId=loss&forceVP9=true&produce=false

In tab 2, select the preferred layers (0,0). Many packets are discarded by the codec, and SeqManager starts generating incorrect sequence numbers.

It takes several minutes, meaning there is a lot of info.
